### PR TITLE
introduce initcontainer to fix env vars not resolved

### PR DESCRIPTION
**Pull request by jeanpommier**

### CODE REVIEW

**Review by pmauduit — APPROVED** [review]
LGTM so far, but I was wondering if there would be a way to define a function into the helper instead to share a bit the code across objects.

**Comment by edevosc2c** [comment]
Example for using the helper in order to remove some redundancy:

`_helpers.tpl`:
```
{{- define "envsubstbase" -}} 
- name: envsubst
  image: georchestra/k8s-initcontainer-envsubst
  volumeMounts:
  - mountPath: /etc/georchestra
    name: georchestra-datadir
  env:
  - name: DEBUG
    value: "yes"
  - name: SUBST_FILES
    value: "{{ .path }}"
{{- end -}}
```

`templates/geonetwork-4/ogc-api-records-deployment.yaml`:

```
{{- if .Values.georchestra.webapps.geonetwork.ogc_api_records.envsubst.enabled }}
initContainers:
      {{- include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      {{- $p := dict "path" "/etc/georchestra/geonetwork/microservices/ogc-api-records/config.yaml" }}
      {{include "envsubstbase" $p | nindent 6 }}
      - name: ES_HOST
        value: "{{ include "georchestra.fullname" . }}-gn4-elasticsearch-svc"
        {{- include "georchestra.common-envs" . | nindent 8 }}
{{- end }}
```

See https://stackoverflow.com/a/45624384

**Comment by jeanpommier** [comment]
Yes, it would be nice. But it might not be that easy. I'll leave that to Emilien. 

The idea was to have something working. Then, let's improve it, with pleasure ;o)

**Comment by jeanpommier** [comment]
But will this allow to factorize the helper to several deployments ? In every case the path is different and you also might need to pass on some env var

**Comment by edevosc2c** [comment]
Yes to several deployments, it was just an example for ogc-api.

You can pass the envs after that, see the 6th line. The helper is just for the "base".

**Comment by jeanpommier** [comment]
yes, nice. Not so easy to read though

**Review by edevosc2c — APPROVED** [review]
About the helm helpers improvements, I think based on the fact that it wouldn't be as easy to read, we will refrain from implementing this change for the moment. And we will reconsider that in the future.

**Pull request merged**
