### PR TITLE
add rabbitmq support into helm chart

### PR DESCRIPTION
**Pull request by edevosc2c**
# Description

Since https://github.com/georchestra/improvement-proposals/issues/6 was accepted and the support for rabbitmq was recently merged into georchestra/docker: https://github.com/georchestra/docker.

This pull request adds the support for rabbitmq. It uses bitnami rabbitmq well maintained helm chart, same author of the helm chart that we are using for postgresql.

Almost all the logic was copied from the postgresql component, same ability to set a custom secret and same structure for the YAML.

# Technical notes about the changes in this PR

- This upgrades the postgresql helm chart version, I had to update it because there was a conflict with the rabbitmq helm chart.
- This separate each helm helpers for more readability.
- This add the support of rabbitmq through helm chart of bitnami organization.

# Notes - to discuss

The issue, to discuss, is that the georchestra gateway hasn't been set by default, so rabbitmq is not mandatory yet for georchestra.

This means one can turn off rabbitmq (`rabbitmq.builtin: false`) but there will still be a need to fill something in the `rabbitmq.auth` section because the helm chart consider that if you turn off the builtin rabbitmq then you must provide an external rabbitmq server then.

One solution to this is to add a new parameter called `rabbitmq.enabled` which if "false" stop provisioning anything related to rabbitmq into the chart. But the name could confuse some people with the parameter `builtin: true`

I'm not sure how to tackle this issue. @jeanmi151 @jeanpommier  any ideas?

### CODE REVIEW

**Comment by edevosc2c** [comment]
> One solution to this is to add a new parameter called `rabbitmq.enabled` which if "false" stop provisioning anything related to rabbitmq into the chart. But the name could confuse some people with the parameter `builtin: true`

@jeanmi151 @jeanpommier what do you think of this solution for the issue mentioned above?

**Comment by jeanpommier** [comment]
AFAIK, Gateway won't be optional for long, I believe SP is expected for deprecation in Spring 2024.

So, we just need  a short-term solution. I would say that the way you handle it doesn't really matter as long as
- it is properly documented
- by default it keeps the current "stable" setup with SP, no gateway, no rabbitmq. That's the most important. For instance, we shouldn't have blocking side-effects like https://github.com/georchestra/datadir/issues/336

**Comment by jeanpommier** [comment]
- [x] works with SP enabled, gateway disabled and rabbitmq disabled
- [x] works with SP enabled, gateway disabled and rabbitmq enabled
Though it is apparently not supported to perform an upgrade (from rabbitmq disabled to rabbitmq enabled): getting 
```
Error: UPGRADE FAILED: template: georchestra/charts/rabbitmq/templates/statefulset.yaml:39:28: executing "georchestra/charts/rabbitmq/templates/statefulset.yaml" at <include (print $.Template.BasePath "/secrets.yaml") .>: error calling include: template: georchestra/charts/rabbitmq/templates/secrets.yaml:27:29: executing "georchestra/charts/rabbitmq/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "rabbitmq-erlang-cookie" "length" 32 "providedValues" (list "auth.erlangCookie") "context" $)>: error calling include: template: georchestra/charts/database/charts/common/templates/_secrets.tpl:117:6: executing "common.secrets.passwords.manage" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordValidationErrors "context" $.context)>: error calling include: template: georchestra/charts/database/charts/common/templates/_errors.tpl:26:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
```
- [ ] ~works with SP disabled, gateway enabled and rabbitmq enabled~ -> can't say since gateway currently seems broken
- [ ] ~works with SP disabled, gateway enabled and rabbitmq disabled~ -> same here. Not sure this is even a relevant use-case

_I only tested with builtin rabbitmq_

**Comment by edevosc2c** [comment]
>       Though it is apparently not supported to perform an upgrade (from rabbitmq disabled to rabbitmq enabled): getting
> 
> 
> ```
> Error: UPGRADE FAILED: template: georchestra/charts/rabbitmq/templates/statefulset.yaml:39:28: executing "georchestra/charts/rabbitmq/templates/statefulset.yaml" at <include (print $.Template.BasePath "/secrets.yaml") .>: error calling include: template: georchestra/charts/rabbitmq/templates/secrets.yaml:27:29: executing "georchestra/charts/rabbitmq/templates/secrets.yaml" at <include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "rabbitmq-erlang-cookie" "length" 32 "providedValues" (list "auth.erlangCookie") "context" $)>: error calling include: template: georchestra/charts/database/charts/common/templates/_secrets.tpl:117:6: executing "common.secrets.passwords.manage" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordValidationErrors "context" $.context)>: error calling include: template: georchestra/charts/database/charts/common/templates/_errors.tpl:26:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
> PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
>                  Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
>                  Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
> ```
> 

Fixed in https://github.com/georchestra/helm-georchestra/pull/54/commits/aae415f7f255e689e52269edaab97ea09e035a40

Related to issue https://github.com/bitnami/charts/issues/10609#issuecomment-1154369939

**Review by jeanpommier — APPROVED** [review]
Looks good to me. But couldn't really proof-test it, since there is something that prevents gateway from starting (seems unrelated to this PR though)

**Pull request merged**
